name = "mobile-repair-tracker-backend"
main = "dist/server/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production.vars]
FAST2SMS_API_KEY = "your-fast2sms-api-key-here" 